# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import op_service_pb2 as op__service__pb2


class OpExecutorStub(object):
    """算子执行服务，运行在 worker 节点上，接收 coordinator 的远程算子调用
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteOp = channel.unary_unary(
                '/gpu_share.OpExecutor/ExecuteOp',
                request_serializer=op__service__pb2.ExecuteOpRequest.SerializeToString,
                response_deserializer=op__service__pb2.ExecuteOpResponse.FromString,
                )


class OpExecutorServicer(object):
    """算子执行服务，运行在 worker 节点上，接收 coordinator 的远程算子调用
    """

    def ExecuteOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteOp': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOp,
                    request_deserializer=op__service__pb2.ExecuteOpRequest.FromString,
                    response_serializer=op__service__pb2.ExecuteOpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpu_share.OpExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpExecutor(object):
    """算子执行服务，运行在 worker 节点上，接收 coordinator 的远程算子调用
    """

    @staticmethod
    def ExecuteOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gpu_share.OpExecutor/ExecuteOp',
            op__service__pb2.ExecuteOpRequest.SerializeToString,
            op__service__pb2.ExecuteOpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
