# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: op_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10op_service.proto\x12\tgpu_share\"C\n\x10\x45xecuteOpRequest\x12\x0f\n\x07op_name\x18\x01 \x01(\t\x12\x0f\n\x07tensors\x18\x02 \x03(\x0c\x12\r\n\x05token\x18\x03 \x01(\t\"#\n\x11\x45xecuteOpResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x32T\n\nOpExecutor\x12\x46\n\tExecuteOp\x12\x1b.gpu_share.ExecuteOpRequest\x1a\x1c.gpu_share.ExecuteOpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'op_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTEOPREQUEST']._serialized_start=31
  _globals['_EXECUTEOPREQUEST']._serialized_end=98
  _globals['_EXECUTEOPRESPONSE']._serialized_start=100
  _globals['_EXECUTEOPRESPONSE']._serialized_end=135
  _globals['_OPEXECUTOR']._serialized_start=137
  _globals['_OPEXECUTOR']._serialized_end=221
# @@protoc_insertion_point(module_scope)
